### ISSUE TITLE
Fabric of Reality cannot be mined by a Digital Miner in Silk Touch Mode

### ISSUE THREAD

**Issue by luckywarp** [StevenRS11/DimDoors#118]
You told me to put it here so I did. :)

**Comment by SenseiKiwi** [comment]
Alright, I have an answer on this finally. Aidan told me that Digital Miners cannot mine blocks using Silk Touch mode if the blocks only drop things if silk touched. In theory, you also couldn't mine up glass or ice. So this isn't a bug on our end, this is a limitation of Digital Miners.
