### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by ghost** [StevenRS11/DimDoors#137]
The issue stuff: http://pastebin.com/GHgEQXEA

And dont try to pass it along to chicken bones. It's your issue for not safety checking. If you want to argue over if it's yours or chicken bones, go ahead. I hope you aren't that kind of person. I dont mean to be a jackass but modders always seem to try to pass it along and I want to prevent that.

Also: This is NOT MY ISSUE. I am reporting it for the forums thread linked in the pastenbin.

**Comment by CannibalVox** [comment]
I apologize for screwing up the PR process, but I submitted PR 140 to fix this issue.

**Comment by SenseiKiwi** [comment]
Alright! So after several hours of mulling this over, I'd simply like to say that...

"I dont mean to be a jackass" - And yet you are being a jackass. This is certainly not the way to post about any issues here. I've never talked to you nor given you a reason to address me like that. I don't even know who you are. So in the future, I hope you never write another post like this again. If you can't be polite, then please don't bother writing to us at all.

**Comment by ghost** [comment]
1. I never said anything about you?
2. I HAVE to write it like that. I am sick of modders always going "it's his fault" "no, it's YOUR fault!" ect and then nothing gets done.

@CannibalVox Great.

**Comment by StevenRS11** [comment]
@zeuslightning125 
...
Look, if you are going to be a jackass, (which is sometimes a good way to make things happen, ill admit), don't be all weaselly about it. You will get much more respect if you acknowledge it, and don't try to make excuses for your behavior as you do it. That's nuts.

Also, SenseiKiwi is a DD dev, so you _are_ talking to him. He fixed the issue, as well.
